apiVersion: v1
kind: Secret
metadata:
  name: postgresql-hms-secret
type: Opaque
data:
  pgadminpassword: cHhKOVBsMDNaTVpHd2FYSQ==
  pgpassword: cHhKOVBsMDNaTVpHd2FYSQ==
  pgreplpassword: cHhKOVBsMDNaTVpHd2FYSQ==
  
