# Default values for hms_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tpipino/hms
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: "hms"

service:
  type: ClusterIP
  port: 9083

livenessProbe:

readinessProbe:

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: myhms.tpi.com
      paths:
        - path: /
          pathType: Prefix

envVar:
  - name: DATABASE_HOST
    value: "my-postgres-hms-pg-hms.hms"
  - name: DATABASE_DB
    value: "postgres"
  - name: DATABASE_USER
    value: "postgres"
  - name: DATABASE_PASSWORD
    value: "pxJ9Pl03ZMZGwaXI"
  - name: AWS_ACCESS_KEY_ID
    #value: ""
    value: "XpVtRFzBR1alEMoHQpzl"
  - name: AWS_SECRET_ACCESS_KEY
    #value: ""
    value: "kECKgqgT5ZJeHsQowfjvqAbHpHp1zg00NthC5YYf"
  - name: S3_ENDPOINT_URL
    #value: ""
    value: "http://iceberg-storage-hl.minio-iceberg:9000"
  - name: S3_BUCKET
    value: "hive"
  - name: S3_PREFIX
    value: "warehouse"
