# Default values for hms_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tpipino/hms
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: "hms"

service:
  type: NodePort
  port: 9083

livenessProbe:

readinessProbe:

secret:
  name: "hms-secret"

env:
  normal:
    DATABASE_HOST: "my-postgres-hms-pg-hms.hms"
    DATABASE_DB: "postgres"
    S3_ENDPOINT_URL: "http://iceberg-storage-hl.minio-iceberg:9000"
    S3_BUCKET: "hive"
    S3_PREFIX: "warehouse"
  secret:
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: "pxJ9Pl03ZMZGwaXI"
    AWS_ACCESS_KEY: "sOmTvPqXnNI0lRkDsLN4"
    AWS_SECRET_ACCESS_KEY: "YXyccWiY0v9I5GsyN6fK00auIuRNlj47OXD0fjcr"
