apiVersion: v1
kind: Secret
metadata:
  name: openmeta-secret
type: Opaque
data:
  pgadminpassword: ZjJGN3VRZThTOHQ2eGJ3REg5Nlk=
  pgpassword: ZjJGN3VRZThTOHQ2eGJ3REg5Nlk=
  pgreplpassword: ZjJGN3VRZThTOHQ2eGJ3REg5Nlk=
  POSTGRES_OPENMETA_USER: b3Blbm1ldGE=
  POSTGRES_OPENMETA_PASSWORD: b3Blbm1ldGFQV0QxMjM=
  AIRFLOW_OPENMETA_USER: YWlyZmxvdw==
  AIRFLOW_OPENMETA_PASSWORD: YWlyZmxvd1BXRDEyMw==
  
  

  
