apiVersion: v1
kind: Secret
metadata:
  name: trino-secret
type: Opaque
data:
  POSTGRES_TEST_USER: cG9zdGdyZXM=
  POSTGRES_TEST_PASSWORD: ZjJGN3VRZThTOHQ2eGJ3REg5Nlk=
  POSTGRES_HMS_USER: cG9zdGdyZXM=
  POSTGRES_HMS_PASSWORD: cHhKOVBsMDNaTVpHd2FYSQ==
  ICEBERG_S3_ACCESS_KEY: c09tVHZQcVhuTkkwbFJrRHNMTjQ=
  ICEBERG_S3_SECRET_KEY: WVh5Y2NXaVkwdjlJNUdzeU42ZkswMGF1SXVSTmxqNDdPWEQwZmpjcg==
  KEYCLOAK_SECRET: UXgyOFB3Z3JPdk9uNDdOTmhMeW1BbW94dVBEU2JwU0w=
  COM_SHARED_SECRET: QUJDREVGRzEyMzQ1Ngo=
  LDAP_BIND_USER: Y249YWRtaW4sZGM9ZGF0YXBsYXRmb3JtLGRjPW9yZwo=
  LDAP_BIND_PW: YWRtaW5wYXNzd29yZAo=
  

  
