apiVersion: v1
kind: Service
metadata:
  name: postgresql-test-nodeport
  labels:
    name: postgresql-test-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 31432
  selector:
    app.kubernetes.io/name: pg-test
